### PR TITLE
Add rich context to details page

### PR DESCRIPTION
**Pull request by svasandani**
Adds rich context to details

localhost_3000_overview_name=Art%20Therapy (1)

### CODE REVIEW

**Comment by rebeccashi** [comment]
I really like the details you added. I think it makes sense to provide links to relevant resources, since we can't provide access to all of those things ourselves. Some suggestions:
1. Can we make the description and historical trends column (cards on the left) wider? Right now, we can only see a very small portion of the description. Maybe that's intentional, but I think we can display a slightly longer description. And the graph is a key part of the information we're displaying, so I think it makes sense for it to take up more space on the screen. Also, there is a lot of white space in the "useful tools" and "search for jobs" cards right now.
Screen Shot 2021-12-04 at 10 29 46 PM

2. I like how are we using wikipedia as a resource, but it doesn't seem like we're displaying the pronunciation correctly. Maybe we can get rid of the pronunciation when parsing data. 
Screen Shot 2021-12-04 at 10 29 46 PM

3. Right now the detail tab of relevant items = details + overview page. That's a huge overlap of functions and I think we are displaying too much information for details. That plus the overview page on top makes the user have to scroll a lot. I think we should only display the `details` card, and if the user want to learn more about that item, they can click on `explore title`. 
Screen Shot 2021-12-04 at 10 57 57 PM

**Comment by svasandani** [comment]
1. I think the graph and contextual information should have equal importance. Users don't necessarily want to see exact values from the graph, just trends, and for that purpose the smaller view works better.
2. There's no one-to-one mapping between our items and Wikipedia, so it just searches for the closest match. We can try to tweak it to be more accurate, but that's out of scope for this PR.
3. I don't see the purpose of forcing users to click an extra button and reload the entire view to engage with the data. There's an overlap but I think because the positions are so separate there is no confusion regarding function. The ideal flow in my mind is: user searches for title/company, explores the relevant skills, and links out when they are interested. This streamlines that flow.

**Comment by svasandani** [comment]
[UPDATE]

1. Made the description and graphs slightly bigger
2. No change
3. Didn't remove anything, but moved trends above the redundant cards so users see it earlier

**Comment by rebeccashi** [comment]
1. The reason why I think the graph should be larger than `userful tools` and `search for jobs` is because that's the information we are providing. Links to other sites is not really where we provide value to our users. Plus the graph just physically takes up more space, whereas the cards with the links have a lot more whitespace. (Thanks for making the left cards bigger)
2. Can we parse out the pronounced part? It's not displaying on our website correctly. I agree on addressing the search later.
3. I see what you're saying about for example letting users compare two companies under a title. But when we compare for example two companies, we only see the graph of the two companies' trends anyways, and we're not really comparing the other information. It just doesn't make sense how we're giving users access to more information about a relevant item than the item that the overview page is dedicated to.

**Comment by svasandani** [comment]
1. :shipit: 
2. It's not consistent across all Wikipedia results, so there's no quick fix even for parsing pronunciation out. There may be some way to get a easier resolution messing with the API, but that'll take some refactoring.
3. I think the differentiator between the relevant item and the overview item (e.g. JavaScript in your screenshots) is that the overview item displays all relevant items. The only way to see that info for any item is to go to its overview page, so having the links for both doesn't change the information hierarchy imo.

**Comment by rebeccashi** [comment]
Compromise on the third point: `search for jobs` and `useful tools` will be reviewed from the detail view.

**Review by rebeccashi — APPROVED** [review]

**Pull request merged**
